travis:
  secure:
    BINSTAR_TOKEN: zizy+Ry2DwLHkPKzY0i43Yqb1nJezK8NOcLdHvrjEyGjyk5p/0j6rWCd/TYXl10VfLyaBSQGO9DL0GsNX8zZHSR43D5DKoS/lU/Ks3/ZGv6Px5/JkSa4WmmmX+L8eFjufygGTeqc3tBzVu7OWszjpawBuVawBjevZ7d5WYOVogeg5nos1g1MSzxNNVptTFxkQzbtxi9d0SeK2KOhxa3fqpfuTj50nHurJXOJgSE+VB0T5FbnqImuW+TPUt1ucIICqVRPGkmCPIY+nf+FuY+6G881GcABHzb9eKDjwTEzXnLxl9ts1hcx/wPSF/3r0kCMb3ZQzfCJbs/OB1+Fo59NtZldJyEC5Gt0uDLbDMnuB1t0MiLRCM+zUQsD25AEtDlOHScCuwSlRdcyFCuWDipBSmzzgvOZ+4bXBIc0x25lrFSyKiinI02L+jzabmvNj4w411agafMEamsNMm93MgQb/3uqP3l8aTLMlzpl04Bje8c24L1CbbcderoI9gKsJyK8MjeSRkFqzbe9mRRrLBm1hXHWHu6Lz9t9/kCoJQJHNLdJOyGg1QKUhBNnXIiLZNzUSjmJlzD72RCyGlyQIXkuSSf6iZ1zUsZ2HwhJwkZyX/1i9m12EjqneXWzAVRqN31aMWAW8KKO4Ku1+KrPB3i+Ci1BEWRqoVnvJT80jom4DNc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
